apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: rex-wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: nginx
  type: NodePort