apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: rex-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginx
    spec:
      volumes:
        - name: config-default
          configMap:
            name: config-default
      containers:
      - name: nginx
        image: nginx:1.21.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
          - name: config-default
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf