apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: rex-wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
  type: ClusterIP