apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: rex-wordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
  clusterIP: None  